defaults:
  - _base_

_target_: rtext.sentence_optimization.train.AttackerGumbel

lr: 1e-1
temperature: 1.0

dice_weight: 5
bce_weight: 1
sim_weight: 200
perp_weight: 1

num_iters: 200
num_samples: 1

crop_attack: False