defaults:
  - _base_

_target_: rtext.sentence_optimization.train.AttackerSonarPerplexity

lr: 0.0003
temperature: 1.0
# softmax_temperature: 0.1
dice_weight: 1
bce_weight: 0
sim_weight: 0
perp_weight: 0
entropy_weight: 0

num_iters: 30

crop_attack: False
