pretrained_model_name_or_path: ./pretrained_weights/weights_custom_adv
name: lisa-7b-v1

dataset_class: lisa.utils.dataset.ValDataset
conv_type: llava_v1

# seg model keys
out_dim: 256
ce_loss_weight: 1.0
dice_loss_weight: 0.5
bce_loss_weight: 2.0
seg_token_idx: !!null
vision_tower: openai/clip-vit-large-patch14
use_mm_start_end: True
low_cpu_mem_usage: True
num_image_tokens: 256
precision: bf16
train_mask_decoder: True

# tokenizer keys
model_max_length: 512
padding_side: right
use_fast: False
cache_dir: !!null
legacy: True
